version: "2"
services:
    golang:
        build: ./go-image
        container_name: go
        volumes:
          - ./pkgconfig:/usr/lib/pkgconfig
          - ./go:/go
        ports:
          - 80:80
          - 443:443
        command: bash -c "go run src/cert/cert.go --host=localhost && go get ./src/api && go run src/api/api.go"
        environment:
          - GOARCH=amd64
          - GOOS=linux
          # - GOOS=windows
          # - CGO_ENABLED=1
          # - CC=x86_64-w64-mingw32-gcc
          # - CXX=x86_64-w64-mingw32-g++