# This is golang
# VERSION 1
# Author: nutchawat

FROM golang

MAINTAINER nutchawat pnutchaw@gmail.com

# install require software
RUN apt-get update && apt-get install -y \
    unzip \
    vim \
    pkg-config \
    libaio1 \
    wget

RUN mkdir -p /usr/lib/oracle/12.1/client64/lib \
    && mkdir -p /usr/include/oracle/12.1/client64/

ENV LD_LIBRARY_PATH /usr/lib:/usr/local/lib:/usr/lib/oracle/12.1/client64/lib
ENV NLS_LANG AMERICAN_AMERICA.AL32UTF8

RUN cd /tmp \
	&& wget https://s3.amazonaws.com/merofile/instantclient-basic-linux.x64-12.1.0.2.0.zip \
	&& wget https://s3.amazonaws.com/merofile/instantclient-sdk-linux.x64-12.1.0.2.0.zip

RUN unzip /tmp/instantclient-basic-linux.x64-12.1.0.2.0.zip -d /tmp \
	&& cp /tmp/instantclient_12_1/* /usr/lib/oracle/12.1/client64/lib/ \
	&& ln -s /usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1 /usr/lib/oracle/12.1/client64/lib/libclntsh.so \
	&& ln -s /usr/lib/oracle/12.1/client64/lib/libclntshcore.so.12.1 /usr/lib/oracle/12.1/client64/lib/libclntshcore.so \
    && ln -s /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1 /usr/lib/oracle/12.1/client64/lib/libocci.so \
    && rm -rf /tmp/instantclient_12_1 \
	&& unzip /tmp/instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /tmp \
    && cp /tmp/instantclient_12_1/sdk/include/* /usr/include/oracle/12.1/client64/ \
    && rm -rf /tmp/*

#RUN go get github.com/mattn/go-oci8
